load("@aspect_rules_js//npm:defs.bzl", "npm_package")

npm_package(
    name = "game-logic",
    srcs = [
        "index.js",
        "package.json",
    ],
    package = "@endor-integration/game-logic",
    root_paths = [
        package_name(),
    ],
    visibility = ["//visibility:public"],
)
